---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  vars:
     go_version: "1.21.5"
     go_arch: "linux-amd64"
     compose_version: 2.23.3
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: "roles/configure-system"
    - {role: docker, become: yes}
    - {role: go , become: yes}
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - golang.Go
            #- GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
    - role: vscode-settings

