---
- name:  Import VSCode vscode-settings
  copy: 
    src: keybinding.json
    dest: /home/{{ ansible_user_id }}/.config/Code/User/keybindings.json
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644